[package]
name = "rust-pow2"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_pow2"
path = "src/lib.rs"

[[bin]]
name = "rust_pow2"
path = "src/main.rs"

[dependencies]
itertools = "0.13.0"
rayon = "1.10.0"
